server:
  port: 8080
  servlet:
    context-path: /library

jwt:
  secret: fyhsdhjkgfhjksfghjkg34ghjcjm
  expiration: 864000000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    jwt:
      secret: ${jwt.secret}
      expiration: ${jwt.expiration}



